// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bloom-directions/Cinematic.tsx": () => import("../components/mockups/bloom-directions/Cinematic.tsx"),
  "./components/mockups/bloom-directions/Cyber.tsx": () => import("../components/mockups/bloom-directions/Cyber.tsx"),
  "./components/mockups/bloom-directions/Glass.tsx": () => import("../components/mockups/bloom-directions/Glass.tsx")
};
